version: 2
jobs:
    build:
        docker:
            - image: buildpack-deps:trusty # primary container will run Ubuntu Trusty
        steps:
            - checkout
    build-live:
        machine:
            enabled: true
        steps:
            - add_ssh_keys:
                fingerprints:
                    - "d7:4a:bc:e5:af:70:e2:94:e2:c2:6f:9d:f7:81:bc:12"
            - deploy:
                name: ssh to laptop
                command: ssh -o "StrictHostKeyChecking no" adan@45.50.226.163 "cd ~/adanconsstanzo.com/frontend/; git checkout .; git pull; npm rebuild node-sass; npm install; npm run build;"

workflows:
    version: 2 
    build-and-deploy:
        jobs:
            - build
            - build-live:
                requires:
                    - build
                filters:
                    branches:
                        only: master