version: 2
jobs:
    build:
        docker:
            - image: buildpack-deps:trusty # primary container will run Ubuntu Trusty
        steps:
            - checkout
    build-live:
        machine:
            enabled: true
        steps:
            - add_ssh_keys:
                fingerprints:
                    - "d8:4c:df:86:65:f1:b5:23:73:b9:62:d4:57:1f:89:c1"
            - deploy:
                name: ssh to laptop
                command: ssh -o "StrictHostKeyChecking no" adan@45.50.226.163 "cd ~/adanconsstanzo.com/frontend/; git checkout .; git pull;"

workflows:
    version: 2 
    build-and-deploy:
        jobs:
            - build
            - build-live:
                requires:
                    - build
                filters:
                    branches:
                        only: master